"""Bounded context packaging and multimodal sanitization."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, Mapping, Optional


FLASH_BUDGET = 80_000
PRO_BUDGET = 240_000


@dataclass(frozen=True)
class TaskContext:
    task: str
    relevant_files: Mapping[str, str]
    relevant_diff: str = ""
    constraints: str = ""
    expected_output: str = ""
    visual_context: Optional[Mapping[str, Any]] = None

    def render(self, mode: str) -> str:
        budget = FLASH_BUDGET if mode == "flash" else PRO_BUDGET
        sections = ["TASK", self.task.strip()]
        if self.relevant_files:
            sections.extend(["RELEVANT FILES", _render_files(self.relevant_files)])
        if self.relevant_diff:
            sections.extend(["RELEVANT DIFF", self.relevant_diff])
        if self.constraints:
            sections.extend(["CONSTRAINTS", self.constraints])
        if self.expected_output:
            sections.extend(["EXPECTED OUTPUT", self.expected_output])
        if self.visual_context:
            sections.extend([
                "PARENT-GENERATED VISUAL CONTEXT",
                "The following image description was generated by the parent Codex agent. "
                "Do not assume access to the original image.",
                str(dict(self.visual_context)),
            ])
        return _bounded("\n\n".join(sections), budget)


def _render_files(files: Mapping[str, str]) -> str:
    return "\n\n".join(f"--- {name} ---\n{content}" for name, content in files.items())


def _bounded(value: str, budget: int) -> str:
    if len(value) <= budget:
        return value
    # Keep headers and tails (diffs and diagnostics commonly carry the answer).
    head = int(budget * 0.75)
    return value[:head] + "\n\n[context truncated at the model budget]\n\n" + value[-(budget - head - 44):]


def sanitize_context(value: Any) -> str:
    """Convert attachments/binary markers into a parent-only text warning."""
    if isinstance(value, str):
        return value
    if isinstance(value, Mapping):
        unsupported = [key for key in value if str(key).lower() in {"image", "images", "binary", "attachment", "screenshot", "video", "pdf"}]
        if unsupported:
            return "Unsupported original attachments were withheld by the parent Codex: " + ", ".join(map(str, unsupported))
        return str(dict(value))
    if isinstance(value, Iterable) and not isinstance(value, (bytes, bytearray)):
        return "\n".join(sanitize_context(item) for item in value)
    if isinstance(value, (bytes, bytearray)):
        return "Binary content was withheld by the parent Codex."
    return str(value)
