"""Bounded context packaging and multimodal sanitization."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict, Iterable, Mapping, Optional


FLASH_BUDGET = 80_000
PRO_BUDGET = 240_000


@dataclass(frozen=True)
class TaskContext:
    task: str
    relevant_files: Mapping[str, str]
    relevant_diff: str = ""
    constraints: str = ""
    expected_output: str = ""
    visual_context: Optional[Mapping[str, Any]] = None

    def render(self, mode: str) -> str:
        budget = FLASH_BUDGET if mode == "flash" else PRO_BUDGET
        sections = ["TASK", self.task.strip()]
        if self.relevant_files:
            sections.extend(["RELEVANT FILES", _render_files(self.relevant_files)])
        if self.relevant_diff:
            sections.extend(["RELEVANT DIFF", self.relevant_diff])
        if self.constraints:
            sections.extend(["CONSTRAINTS", self.constraints])
        if self.expected_output:
            sections.extend(["EXPECTED OUTPUT", self.expected_output])
        if self.visual_context:
            sections.extend([
                "PARENT-GENERATED VISUAL CONTEXT",
                "The following image description was generated by the parent Codex agent. "
                "Do not assume access to the original image.",
                str(dict(self.visual_context)),
            ])
        return _bounded("\n\n".join(sections), budget)


def _render_files(files: Mapping[str, str]) -> str:
    return "\n\n".join(f"--- {name} ---\n{content}" for name, content in files.items())


def _bounded(value: str, budget: int) -> str:
    if len(value) <= budget:
        return value
    # Keep headers and tails (diffs and diagnostics commonly carry the answer).
    head = int(budget * 0.75)
    return value[:head] + "\n\n[context truncated at the model budget]\n\n" + value[-(budget - head - 44):]


_UNSUPPORTED_KEYS = {"image", "images", "binary", "attachment", "screenshot", "video", "pdf"}


def sanitize_context(value: Any) -> str:
    """Recursively remove original attachments before provider transmission."""
    return _sanitize_context(value, set())


def _sanitize_context(value: Any, seen: set[int]) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (bytes, bytearray)):
        return "Binary content was withheld by the parent Codex."
    identity = id(value)
    tracked = isinstance(value, (Mapping, Iterable))
    if tracked:
        if identity in seen:
            return "Cyclic context content was withheld by the parent Codex."
        seen.add(identity)
    try:
        if isinstance(value, Mapping):
            unsupported = [key for key in value if str(key).lower() in _UNSUPPORTED_KEYS]
            if unsupported:
                return "Unsupported original attachments were withheld by the parent Codex: " + ", ".join(map(str, unsupported))
            return str({str(key): _sanitize_context(item, seen) for key, item in value.items()})
        if isinstance(value, Iterable):
            return "\n".join(_sanitize_context(item, seen) for item in value)
        return str(value)
    finally:
        if tracked:
            seen.discard(identity)
